version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  playlist-loader:
    build: ./playlist_loader
    container_name: playlist-loader
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/code/playlist_loader
    volumes:
      - ./playlist_loader:/code
      - ./data:/data  # Bind mount for the data directory
    depends_on:
      - redis
  video-creator:
    build: ./video_creator
    container_name: video-creator
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/code/video_creator
    volumes:
      - ./video_creator:/code
      - ./data:/data  # Bind mount for the data directory
    depends_on:
      - redis